version: "3.8"
services:
  nginx:
    image: nginx:alpine
    ports:
    - 80:80
    volumes:
    - ./conf/nginx.conf:/etc/nginx/nginx.conf
    - ./html:/usr/share/nginx/html
  php:
    build:
      context: ./php/
      dockerfile: dockerfile
    volumes:
    - ./html:/var/www/html
    ports:
      - 9000:9000
  mysql:
    image: mysql:5.6
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/my.cnf
    environment:
    - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 3306:3306
  redis:
    build:
      context: ./redis/
      dockerfile: dockerfile
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/logs:/logs
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    container_name: redis1.0
    ports:
      - 6379:6379
    restart: always



